Wscript.Echo("                 *Notices Bulge*")
Wscript.Echo("__        ___           _    _        _   _     _      ")
Wscript.Echo("\ \      / / |__   __ _| |_ ( ) ___  | |_| |__ (_) ___ ")
Wscript.Echo(" \ \ /\ / /| '_ \ / _\`| __|// / __| | __| '_ \| |/ __|")
Wscript.Echo("  \ V  V / | | | | (_| | |_    \__ \ | |_| | | | |\__ \")
Wscript.Echo("   \_/\_/  |_| |_|\__,_|\__|   |___/ \___|_| |_|_|/___/")
